name: Single Build
on:
  workflow_dispatch:
    inputs:
      PLATFORM:
        description: "build for device"
        required: true
        type: choice
        options:
          - rock-5b
          - rock-5a
          - orangepi-5
          - orangepi-5plus
          - indiedroid-nova
          - roc-rk3588s-pc
          - station-m3
          - r58x
          - r58-mini
          - edge2
          - nanopi-r6s
          - nanopc-t6
          # - rk3588-evb is currently failing

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CONFIGURATION: [Debug]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
          acpica-tools \
          binutils-aarch64-linux-gnu \
          build-essential \
          device-tree-compiler \
          gettext \
          git \
          gcc-aarch64-linux-gnu \
          libc6-dev-arm64-cross \
          python3 \
          python3-pyelftools

      - name: Get version tag
        id: get_version_tag
        shell: bash
        run: echo "version=$(git describe --tags --always)" >> $GITHUB_OUTPUT

      - name: Build platform
        shell: bash
        run: |
          ./build.sh --device ${{inputs.PLATFORM}} --release ${{matrix.CONFIGURATION}}
           mv RK3588_NOR_FLASH.img ${{inputs.PLATFORM}}_UEFI_${{matrix.CONFIGURATION}}_${{steps.get_version_tag.outputs.version}}.img

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{inputs.PLATFORM}} UEFI ${{matrix.CONFIGURATION}} image
          path: ./*.img
          if-no-files-found: error
